spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reservation_db
    username: postgres
    password: 1976
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql


server:
  port: 8081